// <auto-generated />
namespace Chirping.Web.Api.Security.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Moved_UserApplicationManager : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Moved_UserApplicationManager));
        
        string IMigrationMetadata.Id
        {
            get { return "201501270916195_Moved_UserApplicationManager"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
